### ISSUE TITLE
chrono-tz phf dependency

### ISSUE THREAD

**Issue by chronocrate** [WithSecureLabs/chainsaw#100]
Trying to compile this in Kali 5.5.0-kali2-amd64 and getting the error below.  I tried deleting the ./cargo/registry folder according to this [https://blog.illixion.com/2021/10/fix-failed-to-select-a-version-cargo/](url) but that yielded the same results.  Is this a Kali repository issue?

failed to select a version fort he requirment 'phf = "=0.11.1"`
candidate versions found which didn't match: 0.10.1, 0.10.0, 0.9.0, ...
location searched: crates.io index
required by package 'chrono-tz v0.6.3`
    ... which satisfies dependency 'chrono-tz = "0.6.3"` of package 'chain
saw v2.1.0

**Comment by redhunt45** [comment]
I experienced the same issues with Ubuntu 22.04. I removed cargo after installing it with apt-get install cargo.  I installed Rust with rustup listed on the official rust site and then I was able to compile Chainsaw with any further issues.  
https://www.rust-lang.org/tools/install

**Comment by KRUXLEX** [comment]
Try tune in sudo. It must install new lib on root directory. Have same issue

**Comment by chronocrate** [comment]
I'll give that a try tomorrow.  Thanks in advance.

**Comment by alexkornitzer** [comment]
@chronocrate, if you install using rustup it will install the latest rust and cargo. 

https://rustup.rs

**Comment by chronocrate** [comment]
That worked, I had a path issue in addition but it's sorted now.  Thanks a
lot!
