### ISSUE TITLE
Count column

### ISSUE THREAD

**Issue by mkwired** [WithSecureLabs/chainsaw#103]
The behavior of Chainsaw does not work as I thought.  I assumed the output column 'count' represents the number of occurrences of that specific event, but based on my EVTX files, that does not appear correct.  So what does the 'column' mean?

![Clipboard04](https://user-images.githubusercontent.com/649308/193691767-64364a55-d50f-4a1c-9505-208ed6e05977.png)

**Comment by alexkornitzer** [comment]
Hey, so the count in this context it about how many documents were needed to cause the detection to fire. Thus it is only really there to inform users when aggregation based rules trigger such as brute force attacks. The reason it is shown in every row is for consistency. Very happy to change or improve things, do you have any thoughts on it?

**Comment by Sub-Z3r0** [comment]
Hi, is it possible to concatenate results of a column whenever trying to perform an aggregation.
For instance, trying to perform an aggregation rule for a brute force attack and I need to concatenate all of the source IPs into a single cell. is that feasible ?

**Comment by alexkornitzer** [comment]
I believe that is doable in the way that I wrote it, are you wanting to aggregate by multiple columns or just one? The chainsaw rule syntax should already support both use cases: https://github.com/WithSecureLabs/chainsaw/blob/master/rules/login_attacks/account_brute_force.yml

Please let me know if this is not what you meant and we can hash out what is missing in order to get it added in :)

**Comment by alexkornitzer** [comment]
Having said that I have not wired up the fancy outputting for aggregates yet which I think is what you want? https://github.com/WithSecureLabs/chainsaw/blob/master/src/cli.rs#L347

How would you want the columns to concat? As arrays?

**Comment by Sub-Z3r0** [comment]
I would like to add to the aggregation the ability to concat cells. attached you can see an example. 
In the first screenshot the users and timestamps are each in a row, I would like to concatenate them in a single row if that is feasible. 
<img width="689" alt="Screen Shot 2023-08-30 at 11 45 11 PM" src="https://github.com/WithSecureLabs/chainsaw/assets/114444254/e19fa09b-7b6a-44b8-ac2a-d12be4a54ae2">
<img width="1087" alt="Screen Shot 2023-08-30 at 11 47 04 PM" src="https://github.com/WithSecureLabs/chainsaw/assets/114444254/46ff3e00-9b2e-46d2-bd1e-a4ebd8d23b79">

**Comment by alexkornitzer** [comment]
So you can do the first bit by adding the extra field to the aggregate fields in the rule. The second part of merging the non grouped columns is not implemented yet (it just picks the first doc as show in my second comment above). But in theory this is pretty easy to add so I can add that to my list of things to do.

Rule tweak would be like this:
```
...
aggregate:
  count: '>5'
  fields:
    - Event.EventData.TargetUserName
    - Event.EventData.SourceIP
```

**Comment by alexkornitzer** [comment]
@Sub-Z3r0, if you are able to compile Chainsaw, can you give the laster master branch a go? full aggregation support should be working properly now.

![Screenshot 2023-09-04 at 12 03 23](https://github.com/WithSecureLabs/chainsaw/assets/2750747/edb8784c-05e9-43ac-81c3-6d4124222cd7)

**Comment by Sub-Z3r0** [comment]
@alexkornitzer Thank you for your support. It is working as expected.
![2023-09-11 23 05 56](https://github.com/WithSecureLabs/chainsaw/assets/114444254/2f5ec43c-0c3f-4389-beea-91b8af9c8a88)

**Comment by alexkornitzer** [comment]
No problem, will get that tagged up and released. Thanks for testing.
