### ISSUE TITLE
Incorrect hunt examples displayed

### ISSUE THREAD

**Issue by Marwolf** [WithSecureLabs/chainsaw#104]
Using the latest release (2.1.1), I found the example hunts displayed when executed without any arguments to be out of date and no longer working.

![image](https://user-images.githubusercontent.com/16737510/194647785-78afa239-2414-4c86-a58e-2d2e17024e76.png)

A working updated hunt example would be the following (executed using PowerShell):
`.\chainsaw_x86_64-pc-windows-msvc.exe hunt .\EVTX-ATTACK-SAMPLES\ -s sigma/ --mapping mappings/sigma-event-logs-all.yml -r rules/`

**Comment by FranticTyping** [comment]
@Marwolf - Thanks for pointing this out. This should be fixed now.
