### ISSUE TITLE
Add timestamp format to help output

### ISSUE THREAD

**Issue by m-terlinde** [WithSecureLabs/chainsaw#108]
Hey guys,

thanks for the new major release!

The output of `.\chainsaw.exe hunt -h` sadly does not provide the correct syntax for the timestamps for the `--from` and `--to` option.

I just found the correct format on the GitHub site in the last example.

Could you please add the format to the help output?
I'm not familiar with Rust. Is it as easy as changing https://github.com/WithSecureLabs/chainsaw/blob/master/src/main.rs#L122?

Cheers,
Matthias

**Comment by alexkornitzer** [comment]
What would you like here? An example format in the help output?

**Comment by m-terlinde** [comment]
A simple "YYYY-MM-dd HH:mm" or so would be awesome :)

Giving a concrete example date could be a bit ambiguous, depending on the region.
