### ISSUE TITLE
Deserialization error does't not show responsible file

### ISSUE THREAD

**Issue by m-terlinde** [WithSecureLabs/chainsaw#109]
Hey guys,

if the given evtx folder has a corrupt file, chainsaw 2.2 will fail without telling me, at which file it got stuck. So I don't have a chance to fix it by hand or deleting the file in question.

I used chainsaw 1.1.4 to find the offending file, the error message there outputs the path :D.

In my case, the file was just empty. So maybe a "is file empty"-check before deserialization would make it a bit more robust?

Thanks,
Matthias

**Comment by alexkornitzer** [comment]
Will get that feature back in when I get some time.

**Comment by m-terlinde** [comment]
Thanks a lot!

Your work is much appreciated.
