### ISSUE TITLE
Invalid Tau Key Pair error

### ISSUE THREAD

**Issue by clareesespieces** [WithSecureLabs/chainsaw#114]
Hello, I've downloaded the latest version v.2.3.0 (both Windows and All platforms version) and encountered this error when I tried to run my command:

![image](https://user-images.githubusercontent.com/52844014/211110189-eeab6550-bb38-412e-a4f4-a6e040218cc3.png)

I was looking at this issue https://github.com/WithSecureLabs/chainsaw/issues/3 and saw that we both had similar errors but they used a custom rule. I'm not quite sure why mine did not work even with default rules.

Would appreciate any help.

**Comment by alexkornitzer** [comment]
This was fixed in 382be9a6f8684d922d964f933dac1739b0ab129c, I have released build 2.3.1 for this.
