### ISSUE TITLE
Hunt with WEC/WEF

### ISSUE THREAD

**Issue by Flexxi51** [WithSecureLabs/chainsaw#115]
Hello, I really like this project, I think it can be very useful. However, there is a problem when I try to use it. We centralize our logs via WEC, and once the logs are centralized, the "**hunt**" option no longer works, making the tool unusable for companies or centralized log solutions.

Here an example with ForwardedEvent 

```
./chainsaw hunt ForwardedEventsExport/ForwardedEvents.evtx -s sigma-master/rules/windows/builtin/security --mapping mappings/sigma-event-logs-all.yml

 ██████╗██╗  ██╗ █████╗ ██╗███╗   ██╗███████╗ █████╗ ██╗    ██╗
██╔════╝██║  ██║██╔══██╗██║████╗  ██║██╔════╝██╔══██╗██║    ██║
██║     ███████║███████║██║██╔██╗ ██║███████╗███████║██║ █╗ ██║
██║     ██╔══██║██╔══██║██║██║╚██╗██║╚════██║██╔══██║██║███╗██║
╚██████╗██║  ██║██║  ██║██║██║ ╚████║███████║██║  ██║╚███╔███╔╝
 ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝
    By Countercept (@FranticTyping, @AlexKornitzer)

[+] Loading detection rules from: sigma-master/rules/windows/builtin/security
[+] Loaded 150 detection rules (1 not loaded)
[+] Loading forensic artefacts from: ForwardedEventsExport/ForwardedEvents.evtx (extensions: .evtx, .evt)
[+] Loaded 1 forensic artefacts (54.6 MB)
[+] Hunting: [========================================] 1/1                                                                                                                                                                                 [+] 0 Detections found on 0 documents
```

Thanks a lot

**Comment by alexkornitzer** [comment]
Hmm, I thought this was fixed upstream in the evtx parsing library but I guess there are still some samples that are not (https://github.com/WithSecureLabs/chainsaw/issues/25).

Without some sample files I can't really fix this. Are you able to provide any so that I can see what is going on?

**Comment by Flexxi51** [comment]
I found the solution.
My system is not in english, and when the logs are forwarded and parsed to JSON, a lot of key value like EventID become a string type, unlike a local event log which provide an integer for the EventID value.
So we need to edit the sigma rule to match a string and not an int :)
