### ISSUE TITLE
-o flag not recognized

### ISSUE THREAD

**Issue by maikroservice** [WithSecureLabs/chainsaw#141]
Hello, I just tried to run the following command in chainsaw 1.1.7

` .\chainsaw.exe hunt .\evtx_dc --rules .\sigma_rules\ --mapping .\mapping_files\sigma-mapping.yml -o results.txt`

and received the error

`error: Found argument '-o' which wasn't expected, or isn't valid in this context`

when I changed this to `--output` everything worked fine, but the documentation says that -o should also work

**Comment by alexkornitzer** [comment]
Hey, may I ask why you are using version `1` and not version `2` as version `1` is now obsolete? The latest version does not exhibit this bug.

**Comment by maikroservice** [comment]
it's in a closed lab so no chance to update the software, but good to know - thank you for the update
