### ISSUE TITLE
[BUG] Multiple rule matches shift CSV column values

### ISSUE THREAD

**Issue by import-pandas-as-numpy** [WithSecureLabs/chainsaw#180]
**Problem:** With the `--csv` flag, a single event which matches on multiple "rules" (whether Tau or Sigma) will shift the subsequent columns over in CSV output mode.

This is most easily visible in Mimikatz DCSync attacks, where Sigma matches upon both "Active Directory Replication from Non Machine Account" and "Mimikatz DCSync" fields. This results in all subsequent values being "pushed" right. Please see attached screenshot for example. 

**Reproduction:** Unfortunately I cannot supply this event log for demonstration purposes, but finding a Sigma rule and changing the "name" of the rule should be sufficient for replication (as it will now match twice.) 

![image](https://github.com/user-attachments/assets/3ae0ed42-c746-4993-be38-806f231e8339)

**Proposed Fix:**
The "detections" column should likely concatenate matched values as it does in the command line output, and delimit matches by newline within this column. (E.g., `Active Directory Replication from Non Machine Account\nMimikatzDCSync`) The filtering that occurs in CSV output is often accessible enough that this presents a lower hurdle to the user of Chainsaw than arbitrarily rearranging columns.

**Comment by alexkornitzer** [comment]
Will try and have a look into this later today.

**Comment by alexkornitzer** [comment]
Are you able to provide something that can replicate this for me? I have tested this and the concatenation using `;` appears to be working:
<img width="1757" alt="Screenshot 2024-09-10 at 21 19 59" src="https://github.com/user-attachments/assets/ca2fd3bf-4290-4f82-8f95-e2fc76f4ec42">

I ran it with the following duplicating the `create_remote_thread_win_susp_uncommon_target_image.yml` and changing its name:
`chainsaw hunt -s /tmp/sigma/rules/windows/create_remote_thread -m ./mappings/sigma-event-logs-all.yml /tmp/EVTX-ATTACK-SAMPLES --csv --output /tmp/csv`

**Comment by import-pandas-as-numpy** [comment]
Ah, this was a user skill issue. 

LibreOffice, by default, allows an array of valid CSV delimiters, one of which is the `;`. Because of this, 'detections' fields were being delimited unintentionally. 

Closing, cheers for looking, sorry for the bother.
