### ISSUE TITLE
XML2EVTX fails

### ISSUE THREAD

**Issue by ashokchokalingam** [WithSecureLabs/chainsaw#189]
The below is the xml file and i tried converting to  evtx file using jpcert xml2evtx and it was successful but however when i run it through chainsaw it does not work. however, I load it manually on the event viewer and then upload the evtx into chainsaw it works . i am not sure what am i missing here. can someone help me please.

<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Eventlog' Guid='{fc65ddd8-d6ef-4962-83d5-6e5cfe9ce148}'/><EventID>104</EventID><Version>0</Version><Level>Information</Level><Task>Log clear</Task><Opcode>Info</Opcode><Keywords></Keywords><TimeCreated SystemTime='2024-10-29T15:12:37.0387882Z'/><EventRecordID>39493</EventRecordID><Correlation/><Execution ProcessID='1316' ThreadID='19380'/><Channel>System</Channel><Computer>XM</Computer><Security UserID='XM\Administrator'/></System><UserData><LogFileCleared><SubjectUserName>Administrator</SubjectUserName><SubjectDomainName>XM</SubjectDomainName><Channel>System</Channel><BackupPath></BackupPath></LogFileCleared></UserData></Event>
![image](https://github.com/user-attachments/assets/dc0744ba-5158-4041-836b-479814d6c3c4)
![image](https://github.com/user-attachments/assets/f17dd889-6cb3-43c8-90e2-2a06f149a4e4)

**Comment by alexkornitzer** [comment]
Hey @ashokchokalingam,

So the output there can be a bit confusing, that has successfully loaded the file `Loaded 1 forensic artefacts`, but has not mated any rules on any documents `0 Detections found on 0 documents`. In this case documents is the number of documents that detections were found within.

If you run `chainsaw dump` you would see the output of the evtx file.

**Comment by ashokchokalingam** [comment]
Thank you so much for the support.

I have a setup where my log management solution sends Windows logs in
syslog format as XML to an Ubuntu machine. Here's the workflow I follow:

   1. The XML data is received by Logstash, which writes each log as a
   single line into a file.
   2. I use the JPCERT xml2evtx project to convert this XML data into EVTX
   format.
   3. I then apply Chainsaw to the converted EVTX files, but unfortunately,
   Chainsaw doesn't detect anything.

However, if I take the same XML data and load it back into Windows Event
Viewer, then export it as EVTX, Chainsaw successfully processes and detects
items in that file.

Is there something specific about the format or structure of the
XML-to-EVTX conversion using xml2evtx that Chainsaw might be expecting? Any
guidance on this would be highly appreciated.

the log message i tried was event log cleared. if i remember the event id
its 104. it works fine when coming from eventviewer directly the same XML.


Regards

Ashok

**Comment by alexkornitzer** [comment]
Ah right okay, so from a brief look, its looks like the `xml2evtx` script is incorrectly typing fields to strings which is then resulting in them being ignored as Chainsaw will not coerce fields unless explicitly told in rules or mappings.

xml2evtx:
<img width="336" alt="Screenshot 2024-10-31 at 11 31 37" src="https://github.com/user-attachments/assets/668c04f2-f7dd-4fe6-8810-d32f45a58657">

evtx:
<img width="285" alt="Screenshot 2024-10-31 at 11 31 44" src="https://github.com/user-attachments/assets/84a0c38a-a4a5-4d4f-8494-ad98e12e3756">

**Comment by ashokchokalingam** [comment]
it seems to be xml2evtx is not doing the thing correctly, is there any
other tool you could recommend please? or not sure how to fix

**Comment by ashokchokalingam** [comment]
is there a way chainsaw can accept direct json or XML format instead of
evtx? i can convert the XML to json possibly using logstash.


Regards
Ashok

**Comment by alexkornitzer** [comment]
You can tweak the sigma mappings file to coerce those fields into the correct type. Chainsaw also can accept JSON or XML but again the mappings file would need to be tweaked to handle those field changes. So in the groups bit of the mapping the field can be cast like so:

```
- name: Event ID
  from: EventID
  to: Event.System.EventID
  cast: int
```

**Comment by alexkornitzer** [comment]
I would recommend modifying the mapping file for the evtx to use casting. But for JSON, Chainsaw will already recognise that format but the kind `evtx` needs to be changed to `json` in the mapping file.
