### ISSUE TITLE
MFT Alternate Data Streams

### ISSUE THREAD

**Issue by IppSec** [WithSecureLabs/chainsaw#191]
It doesn't look like the MFT Dump outputs Alternate Data Streams, which can be useful to identify files that came from the internet. If we extracted the Resident Files #190  they would appear there, but I believe the ADS should also appear as files in the dump command.

It does look like the entry has an "HasAlternateDataStreams", just doesn't list the names.

**Comment by FranticTyping** [comment]
Just updating this thread. I have a locally working solution, I'm just cleaning it up and doing some testing.

**Comment by FranticTyping** [comment]
@IppSec - The requested features should be available in the latest version of Chainsaw (v2.11.0). You can read about the features here #210 

I'll close this issue now, but please let me know if there are additional changes you need!
