### ISSUE TITLE
Feature Request: Add $MFT Filename Support

### ISSUE THREAD

**Issue by reece394** [WithSecureLabs/chainsaw#192]
This should be a fairly simple thing to fix. Currently when parsing the MFT you have to have the file named either with .mft or .bin so mft.mft or mft.bin. Triage package tools typically collect it as $MFT so it would be a nice fix to not have to rename it to mft.bin before running it through Chainsaw

**Comment by alexkornitzer** [comment]
Good idea, have added that in.

**Comment by reece394** [comment]
Tried testing this with the following command ./chainsaw hunt C:\ChainsawTest\C --rule "C:\Users\TestUser\Desktop\KAPE\KAPE\Modules\bin\chainsaw\rules" --csv --output C:\ChainsawTestParsed --full --skip-errors and unfortunately the fix still did not work. Still need to rename it to mft.bin

**Comment by alexkornitzer** [comment]
Did you compile it from source? It has not been released yet.

**Comment by reece394** [comment]
Yes compiled from source using master branch and 
git clone https://github.com/WithSecureLabs/chainsaw.git
cargo build --release

**Comment by alexkornitzer** [comment]
Sorry about that, I only checked it on `dump` and missed a bit needed for `hunt`. This should be working now.

**Comment by reece394** [comment]
Perfect this works now. Thanks for the quick fix!
