### ISSUE TITLE
did 2.10.1 release get re-tagged

### ISSUE THREAD

**Issue by chenrui333** [WithSecureLabs/chainsaw#197]
👋 seeing some checksum changed while regression build the 2.10.1 release, raise this issue to confirm if there was some re-tagging? Thanks!

```
  Expected: f2130aa7c4d918dd4c96461ab9860348e742e3b50ccc8d02aea92878156eaf8f
    Actual: f2c8d6a3e7d982b8dc5fe95ba17463c1cf2bae44e61a7382bcea5151b6fa174b
```

relates to 
https://github.com/Homebrew/homebrew-core/pull/199434
https://github.com/Homebrew/homebrew-core/pull/199379

**Comment by alexkornitzer** [comment]
Hey,

It was only re-tagged on the day of release the 27th October, while getting the CICD to pass after adding ARM support. So if the release was grabbed during that small debugging window there is a chance the hash could have been incorrect.

**Comment by chenrui333** [comment]
no worries, thanks for confirming it. (might be better to mark as pre-release next time 🙏 )
