### ISSUE TITLE
Support for more F-Secure alerts / log providers

### ISSUE THREAD

**Issue by einarssonm** [WithSecureLabs/chainsaw#26]
Request to add support for more event log providers related to F-Secure alerts. The built-in support for F-Secure alerts consumes events from the "F-Secure Ultralight SDK" provider. My limited research shows that alerts are also found in the "F-Secure File scanning" and "FSecure-FSecure-F-Secure DeepGuard" providers. These alerts aren't detected by Chainsaw.

![image](https://user-images.githubusercontent.com/86156109/138237869-104c6d73-5b5f-4060-868f-edb85da330c9.png)

![image](https://user-images.githubusercontent.com/86156109/138238057-b1d0eabd-92da-4db2-b548-3f65264332d8.png)

(Let me know if there is any good documentation about event ID:s and log providers used by F-Secure.)

**Comment by alexkornitzer** [comment]
As the features required are now exposed that there has been no response or progress with this issue I am going to resolve it out. It can be reopened if required.
