### ISSUE TITLE
Issue with CSV output not populating "Event Data" row

### ISSUE THREAD

**Issue by danielgottt** [WithSecureLabs/chainsaw#96]
Hi Team,

When I output chainsaw detections into a csv I notice the actual data isn't populating within the "Event Data" row. I'll throw my cmdline arguments below along with an example output.

./chainsaw.exe hunt Logs/SOMEFILE.evtx -s sigma/rules/ --mapping mappings/sigma-event-logs-all.yml --full --output results --csv

I am getting detections but nothing is populating within that row 😢
![1](https://user-images.githubusercontent.com/47673777/187451088-5b2e74b2-7eb2-45fd-8b8a-e551cca70f9e.png)
![2](https://user-images.githubusercontent.com/47673777/187451170-7214cace-4f2a-4696-8969-1a12afbc60d1.png)

**Comment by FranticTyping** [comment]
Hey @danielgottt,

The data is there, if you expand the EventData cell downwards you should be able to see it.

let me know if you still have issues :)

**Comment by danielgottt** [comment]
oh boy what a stupid mistake. Appreciate it!
