### ISSUE TITLE
Chainsaw 2 Doesn't Recognize .evt Files

### ISSUE THREAD

**Issue by RossMadness** [WithSecureLabs/chainsaw#99]
Hello there.

First, thank you for the great tool. This has been a wonderful tool in the infosec tool belt.

The issue I'm having may not be an "issue" at all, but a misunderstanding on my part. The EDR I use allows me to collect investigation packages from endpoints and in that package I get a variety of event log files that all end with the extension .evt (not .evtx). Previously I was using Chainsaw 1.1.7 and it recognized the .evt files and parsed them with no issues.

Now that I've downloaded 2.0, it fails to find the .evt files. If I rename the file to .evtx then Chainsaw kicks off like normal and I get results. Am I doing something incorrectly? Did Chainsaw drop support for .evt files?

Thank you again for your time.

**Comment by alexkornitzer** [comment]
Ah good spot, i'll add that additional file type back in. Sorry about that.
